var searchData=
[
  ['schedule_5fat_5fsender_0',['schedule_at_sender',['../structunifex_1_1__thread__unsafe__event__loop_1_1schedule__at__sender.html',1,'schedule_at_sender'],['../classunifex_1_1__timed__single__thread__context_1_1schedule__at__sender.html',1,'schedule_at_sender']]],
  ['schedule_5ftask_1',['schedule_task',['../structunifex_1_1__inline__sched_1_1scheduler_1_1schedule__task.html',1,'unifex::_inline_sched::scheduler']]],
  ['scheduler_2',['scheduler',['../structunifex_1_1__inline__sched_1_1scheduler.html',1,'scheduler'],['../classunifex_1_1__manual__event__loop_1_1context_1_1scheduler.html',1,'context::scheduler'],['../classunifex_1_1__static__thread__pool_1_1context_1_1scheduler.html',1,'context::scheduler'],['../classunifex_1_1__thread__unsafe__event__loop_1_1scheduler.html',1,'scheduler'],['../classunifex_1_1__timed__single__thread__context_1_1scheduler.html',1,'scheduler'],['../classunifex_1_1__trampoline_1_1scheduler.html',1,'scheduler']]],
  ['scope_5fguard_3',['scope_guard',['../structunifex_1_1scope__guard.html',1,'unifex']]],
  ['sender_4',['sender',['../structunifex_1_1__async__trace_1_1sender.html',1,'sender'],['../classunifex_1_1__just__done_1_1sender.html',1,'sender'],['../structunifex_1_1__never_1_1sender.html',1,'sender'],['../structunifex_1_1__ready__done_1_1sender.html',1,'sender'],['../structunifex_1_1__schedule_1_1sender.html',1,'sender']]],
  ['sender_5fbase_5',['sender_base',['../structunifex_1_1sender__base.html',1,'unifex']]],
  ['sender_5ffor_6',['sender_for',['../structunifex_1_1__sf_1_1sender__for.html',1,'unifex::_sf']]],
  ['sender_5ftraits_7',['sender_traits',['../structunifex_1_1sender__traits.html',1,'unifex']]],
  ['sender_5ftraits_3c_20predecessor_5ftype_20_3e_8',['sender_traits&lt; predecessor_type &gt;',['../structunifex_1_1sender__traits.html',1,'unifex']]],
  ['sender_5ftraits_3c_20sender_20_3e_9',['sender_traits&lt; Sender &gt;',['../structunifex_1_1sender__traits.html',1,'unifex']]],
  ['sender_5ftraits_3c_20sender_5ffor_3c_20cpo_2c_20sender_2c_20context_20_3e_20_3e_10',['sender_traits&lt; sender_for&lt; CPO, Sender, Context &gt; &gt;',['../structunifex_1_1sender__traits_3_01sender__for_3_01_c_p_o_00_01_sender_00_01_context_01_4_01_4.html',1,'unifex']]],
  ['sends_5fdone_5fimpl_11',['sends_done_impl',['../structunifex_1_1__let__e_1_1sends__done__impl.html',1,'sends_done_impl&lt; Sender &gt;'],['../structunifex_1_1__let__v_1_1sends__done__impl.html',1,'sends_done_impl&lt; Sender &gt;'],['../structunifex_1_1__retry__when_1_1sends__done__impl.html',1,'sends_done_impl&lt; Sender &gt;']]],
  ['sequenced_5fpolicy_12',['sequenced_policy',['../structunifex_1_1sequenced__policy.html',1,'unifex']]],
  ['set_13',['set',['../structunifex_1_1__aare_1_1async__auto__reset__event.html#a39ff4adf4d7625431d2c3d5d65e1ef96',1,'unifex::_aare::async_auto_reset_event']]],
  ['set_5fdone_14',['set_done',['../structunifex_1_1__aare_1_1async__auto__reset__event.html#a359a2c7da831d63ea1fdb982ca5d39a7',1,'unifex::_aare::async_auto_reset_event']]],
  ['single_5foverload_15',['single_overload',['../structunifex_1_1single__overload.html',1,'unifex']]],
  ['single_5foverload_3c_20overload_20_3e_16',['single_overload&lt; Overload &gt;',['../structunifex_1_1single__overload_3_01_overload_01_4.html',1,'unifex']]],
  ['single_5foverload_3c_20overloads_2e_2e_2e_20_3e_17',['single_overload&lt; Overloads... &gt;',['../structunifex_1_1single__overload.html',1,'unifex']]],
  ['single_5foverload_3c_3e_18',['single_overload&lt;&gt;',['../structunifex_1_1single__overload_3_4.html',1,'unifex']]],
  ['single_5ftype_19',['single_type',['../structunifex_1_1single__type.html',1,'unifex']]],
  ['single_5ftype_3c_20t_20_3e_20',['single_type&lt; T &gt;',['../structunifex_1_1single__type_3_01_t_01_4.html',1,'unifex']]],
  ['single_5fvalue_5ftype_21',['single_value_type',['../structunifex_1_1single__value__type.html',1,'unifex']]],
  ['single_5fvalue_5ftype_3c_20t_20_3e_22',['single_value_type&lt; T &gt;',['../structunifex_1_1single__value__type_3_01_t_01_4.html',1,'unifex']]],
  ['single_5fvalue_5ftype_3c_3e_23',['single_value_type&lt;&gt;',['../structunifex_1_1single__value__type_3_4.html',1,'unifex']]],
  ['source_5freceiver_24',['source_receiver',['../structunifex_1_1__take__until_1_1__stream_1_1type_1_1cleanup__sender_1_1__op_1_1type_1_1source__receiver.html',1,'unifex::_take_until::_stream::type::cleanup_sender::_op::type']]],
  ['span_25',['span',['../structunifex_1_1span.html',1,'unifex']]],
  ['span_3c_20t_2c_20dynamic_5fextent_20_3e_26',['span&lt; T, dynamic_extent &gt;',['../structunifex_1_1span_3_01_t_00_01dynamic__extent_01_4.html',1,'unifex']]],
  ['spin_5fwait_27',['spin_wait',['../classunifex_1_1spin__wait.html',1,'unifex']]],
  ['stop_5fcallback_28',['stop_callback',['../structunifex_1_1__fss_1_1stop__callback.html',1,'unifex::_fss']]],
  ['stream_29',['stream',['../structunifex_1_1__aare_1_1async__auto__reset__event.html#ab561a248004e712d97374152974df46e',1,'unifex::_aare::async_auto_reset_event::stream()'],['../structunifex_1_1__never_1_1stream.html',1,'stream'],['../structunifex_1_1__range_1_1stream.html',1,'stream']]],
  ['stream_5fbase_30',['stream_base',['../structunifex_1_1__type__erase_1_1__stream_1_1type_1_1stream__base.html',1,'unifex::_type_erase::_stream::type']]],
  ['stream_5fview_31',['stream_view',['../structunifex_1_1__aare_1_1async__auto__reset__event_1_1stream__view.html',1,'unifex::_aare::async_auto_reset_event']]]
];
